version: '3.7'

services:
  thelma:
    build:
      context: .
      args:
        ARG_VERSION_MAJOR: 1
        ARG_VERSION_MINOR: 1
        ARG_VERSION_PATCH: 0
        ARG_RELEASE: "pre-alpha"
        DEFAULT_USER: ${DEFAULT_USER}
    restart: always
    ports:
      - "8004:8002"
    environment:
      - "WORKERS=2"
      - "THELMA_SECRET_KEY=${THELMA_SECRET_KEY}"
      - "TELEMETRY_API_HOST=${TELEMETRY_API_HOST}"
      - "TELEMETRY_API_PORT=${TELEMETRY_API_PORT}"
      # - "WEB_ROOT=${WEB_ROOT}"
      - "DJANGO_SETTINGS_MODULE=config.settings.base"
      - "HTTP_PROTOCOL=${HTTP_PROTOCOL}"
    # network_mode: "host"
networks:
  default:
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}